# Generated by Django 4.2.13 on 2024-10-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_country_name_alter_country_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='_wallet_name',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('USDT', 'USDT'), ('LTC', 'LTC')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_id',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
