# Generated by Django 4.2.13 on 2024-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_auto_20220526_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingdeposit',
            name='payment_method',
            field=models.CharField(choices=[('USDT(BEP20)', 'USDT(BEP20)'), ('USDT(TRC20)', 'USDT(TRC20)'), ('ETH', 'ETH'), ('BTC', 'BTC'), ('LTC', 'LTC')], default='direct', max_length=20),
        ),
    ]
