# Generated by Django 4.2.13 on 2024-10-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_alter_pendingdeposit_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=35),
        ),
        migrations.AlterField(
            model_name='withdrawalapplication',
            name='balance_type',
            field=models.CharField(choices=[('Referral', 'Referral'), ('Main', 'Main')], max_length=30),
        ),
        migrations.AlterField(
            model_name='withdrawalapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=30),
        ),
    ]
